"""Throughput that stays honest across a resume.

The Level-2 run trained 32,768,000 tokens in 15,684.6 s — 2,090 tok/s. After resuming at
step 1600 its logs claimed 139,256 tok/s, then 70,945, 48,117, 36,623, decaying to
10,605 by the end.

The decay was the tell. A rate falling as 1/n is a numerator that barely moves over a
denominator growing linearly, and that is exactly what the old code computed: **tokens
accumulated across every session** divided by **the time this session has been running**.
At the first log after resume, 26.6M tokens over ~196 s.

The measurement was fine. The arithmetic mixed two scopes.

Three quantities, kept apart here because collapsing any two of them is the bug:

===================  ====================================  ==========================
quantity             definition                            answers
===================  ====================================  ==========================
interval             tokens since the last report /        did it just get slower?
                     time since the last report
session              tokens this process generated /       what is this GPU doing?
                     time this process has run
run-wide             every token / every second,           what did the experiment cost?
                     including previous sessions
===================  ====================================  ==========================

Only the run-wide figure is comparable to a headline number like "2,090 tok/s", and only
the interval figure reacts to a slowdown while it is happening. Reporting one and calling
it the other is how a 5x overstatement survives to the end of a run.

Time is passed in rather than read, so the arithmetic is testable without sleeping.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ThroughputTracker:
    """Tokens against time, at three scopes that must not be confused.

    ``resumed_*`` describe work done by *earlier* sessions, restored from the checkpoint.
    Everything else is this process. The distinction is the whole point: a resumed run
    inherits a token count, and dividing that by a fresh clock is meaningless.
    """

    #: Tokens generated by previous sessions, from TrainingState.tokens_seen.
    resumed_tokens: int = 0
    #: Wall-clock those sessions took, from TrainingState.elapsed_seconds.
    resumed_seconds: float = 0.0

    #: Tokens generated by this process only.
    session_tokens: int = 0
    #: Session-clock reading at the last report, so the next interval starts there.
    _last_report_s: float = 0.0
    _tokens_at_last_report: int = 0
    _history: list[dict[str, Any]] = field(default_factory=list)

    @classmethod
    def from_state(cls, *, tokens_seen: int, elapsed_seconds: float) -> ThroughputTracker:
        """Build from the two fields the checkpoint already carries.

        Deliberately no new checkpointed state: the information needed to resume
        throughput correctly was always there, it was just used wrongly.
        """
        return cls(resumed_tokens=tokens_seen, resumed_seconds=elapsed_seconds)

    def add_tokens(self, count: int) -> None:
        self.session_tokens += max(0, count)

    @property
    def total_tokens(self) -> int:
        """Every token this experiment has trained on, across all sessions."""
        return self.resumed_tokens + self.session_tokens

    def total_seconds(self, now: float) -> float:
        """Every second this experiment has spent training, across all sessions."""
        return self.resumed_seconds + max(0.0, now)

    def rates(self, now: float) -> dict[str, Any]:
        """Report all three rates and advance the interval window.

        ``now`` is elapsed seconds within this session, not a wall-clock timestamp.
        """
        session_s = max(0.0, now)
        total_s = self.total_seconds(session_s)

        # A monotonic clock should not go backwards, but a bad reading must not produce a
        # negative rate that reads as data.
        interval_s = max(0.0, session_s - self._last_report_s)
        interval_tokens = max(0, self.session_tokens - self._tokens_at_last_report)

        rates = {
            "total_tokens": self.total_tokens,
            "session_tokens": self.session_tokens,
            "elapsed_s": round(total_s, 2),
            "session_elapsed_s": round(session_s, 2),
            # Since the previous report: reacts immediately to a slowdown.
            "interval_tokens_per_second": (
                round(interval_tokens / interval_s, 1) if interval_s > 0 else 0.0
            ),
            # This process only: what the current GPU is sustaining.
            "session_tokens_per_second": (
                round(self.session_tokens / session_s, 1) if session_s > 0 else 0.0
            ),
            # Every session: the only figure comparable to a headline number.
            "tokens_per_second": (
                round(self.total_tokens / total_s, 1) if total_s > 0 else 0.0
            ),
            "resumed": self.resumed_tokens > 0,
        }

        self._last_report_s = session_s
        self._tokens_at_last_report = self.session_tokens
        self._history.append(rates)
        return rates

    def summary(self, now: float) -> dict[str, Any]:
        """Final figures for the run record, without disturbing the interval window."""
        total_s = self.total_seconds(max(0.0, now))
        return {
            "total_tokens": self.total_tokens,
            "elapsed_s": round(total_s, 2),
            "tokens_per_second": (
                round(self.total_tokens / total_s, 1) if total_s > 0 else None
            ),
            "session_tokens": self.session_tokens,
            "session_elapsed_s": round(max(0.0, now), 2),
            "session_tokens_per_second": (
                round(self.session_tokens / now, 1) if now > 0 else None
            ),
            "resumed_tokens": self.resumed_tokens,
            "resumed_seconds": round(self.resumed_seconds, 2),
            "n_sessions_note": (
                "elapsed_s and tokens_per_second span every session this experiment ran "
                "across; session_* cover only the process that wrote this record"
            ),
        }


def recompute_from_history(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Recover correct rates from logs written by the buggy code.

    Usable because every affected record still carries the two fields that matter —
    cumulative ``tokens_seen`` and cumulative ``elapsed_s``. The run-wide rate is
    recoverable exactly; the interval rate is recoverable between consecutive records.
    The originally logged ``tokens_per_second`` is not repaired in place but returned
    alongside, so a corrected log can be diffed against what was printed at the time.
    """
    corrected: list[dict[str, Any]] = []
    previous: dict[str, Any] | None = None
    for record in records:
        tokens = record.get("tokens_seen")
        elapsed = record.get("elapsed_s")
        if tokens is None or elapsed is None:
            continue
        row = {
            "step": record.get("step"),
            "tokens_seen": tokens,
            "elapsed_s": elapsed,
            "logged_tokens_per_second": record.get("tokens_per_second"),
            "tokens_per_second": round(tokens / elapsed, 1) if elapsed else None,
            "interval_tokens_per_second": None,
        }
        if previous is not None:
            delta_tokens = tokens - previous["tokens_seen"]
            delta_seconds = elapsed - previous["elapsed_s"]
            if delta_seconds > 0 and delta_tokens >= 0:
                row["interval_tokens_per_second"] = round(delta_tokens / delta_seconds, 1)
        corrected.append(row)
        previous = row
    return corrected
