"""The whole pipeline on CPU: prompts to teacher data to student loader to evaluation.

The point of the architecture under test is that the teacher and the student never need
to coexist. Generation runs once on hardware big enough for a 27B model and writes a
durable artifact; training reads that artifact weeks later on a free T4. These tests walk
that path end to end with a mock teacher, so the seams are exercised before any GPU time
is spent on them.

Also covered: every way the handoff can go wrong. A dataset that arrives short, edited,
duplicated, or generated by a different teacher than the one claimed.
"""

from __future__ import annotations

import json

import pytest

from qwen_distill.distillation.backends import MOCK_BACKEND, make_backend
from qwen_distill.distillation.dataset import (
    DatasetFilter,
    format_sft_example,
    load_teacher_dataset,
)
from qwen_distill.distillation.generation import Prompt, generate_dataset
from qwen_distill.distillation.manifest import DatasetManifest, ShardRecord, shard_name
from qwen_distill.distillation.objectives import (
    LOGIT_KD,
    MIXED_KD,
    NOT_IMPLEMENTED,
    SFT,
    ObjectiveConfig,
    ObjectiveUnavailable,
    check_dataset_supports,
)
from qwen_distill.distillation.provenance import (
    RunManifest,
    TeacherIdentity,
    sha256_json,
    sha256_text,
)
from qwen_distill.distillation.reasoning_modes import (
    DEFAULT_EFFORT,
    SUPPORTED_MODES,
    UnsupportedReasoningMode,
    resolve_mode,
    sweep_modes,
)
from qwen_distill.evaluation.paired import (
    METRIC_DEFINITIONS,
    PairedRecord,
    accuracy_at_token_budget,
    reasoning_sweep_table,
    summarise_paired,
    summarise_side,
)


def build_dataset(directory, n=12, mode="xhigh", prefix="p", **kwargs):
    prompts = [Prompt(id=f"{prefix}-{i:04d}", prompt=f"{prefix} question {i}",
                      category="math")
               for i in range(n)]
    kwargs.setdefault("teacher_model", "Qwen/Qwen3.8-27B")
    return generate_dataset(
        prompts, make_backend(MOCK_BACKEND), resolve_mode(mode), directory, **kwargs
    )


# --- reasoning modes, from the verified template --------------------------
@pytest.mark.parametrize("name", SUPPORTED_MODES)
def test_every_supported_mode_resolves(name):
    mode = resolve_mode(name)
    assert mode.name == name
    assert mode.template_kwargs(), "a mode must reach the template somehow"


def test_high_is_rejected_because_the_real_template_rejects_it():
    """It reads like it should work. It raises inside the template."""
    with pytest.raises(UnsupportedReasoningMode, match="xhigh, medium and low"):
        resolve_mode("high")


def test_medium_is_not_a_no_op():
    """A widely repeated secondary claim says it is; the template refutes it."""
    medium = resolve_mode("medium")
    assert medium.template_kwargs() == {"reasoning_effort": "medium"}
    assert medium.reasoning_enabled is True
    assert "not a no-op" in medium.description


def test_none_resolves_to_the_templates_default_not_to_no_reasoning():
    assert resolve_mode(None).name == DEFAULT_EFFORT == "xhigh"


def test_thinking_disabled_uses_a_different_control():
    mode = resolve_mode("thinking_disabled")
    assert mode.template_kwargs() == {"enable_thinking": False}
    assert mode.reasoning_enabled is False


def test_an_unknown_mode_lists_the_supported_ones():
    with pytest.raises(UnsupportedReasoningMode, match="thinking_disabled"):
        resolve_mode("turbo")


def test_the_sweep_is_ordered_cheapest_first():
    names = [m.name for m in sweep_modes()]
    assert names == ["thinking_disabled", "low", "medium", "xhigh"]


# --- the end-to-end handoff -----------------------------------------------
def test_prompts_to_teacher_data_to_student_loader(tmp_path):
    """The architectural claim: the student trains from files alone."""
    manifest, stats = build_dataset(tmp_path, n=20, shard_size=8)
    assert stats.generated == 20

    dataset = load_teacher_dataset(tmp_path)

    assert len(dataset) == 20
    assert dataset.stats.n_dropped == 0
    assert dataset.manifest is not None
    # Nothing about the teacher is needed to read this back.
    context, target = format_sft_example(dataset.examples[0])
    assert context and target


def test_the_loader_reads_only_complete_shards(tmp_path):
    """Training on a truncated file changes the dataset out from under a comparison."""
    manifest, _ = build_dataset(tmp_path, n=12, shard_size=5)
    manifest.add_shard(ShardRecord(name=shard_name(0), n_records=5, complete=False))
    manifest.write(tmp_path)

    verified = load_teacher_dataset(tmp_path, verified_only=True)
    everything = load_teacher_dataset(tmp_path, verified_only=False)

    assert len(verified) == 7
    assert len(everything) == 12


def test_the_split_is_deterministic(tmp_path):
    build_dataset(tmp_path, n=20)
    dataset = load_teacher_dataset(tmp_path)

    first_train, first_val = dataset.split(seed=3)
    second_train, second_val = dataset.split(seed=3)

    assert [e.example_id for e in first_val] == [e.example_id for e in second_val]
    assert set(e.example_id for e in first_train).isdisjoint(
        e.example_id for e in first_val
    )
    assert len(first_train) + len(first_val) == 20


def test_the_split_does_not_depend_on_shard_order(tmp_path):
    """Two generation sessions can produce the same dataset in a different order."""
    one, two = tmp_path / "a", tmp_path / "b"
    build_dataset(one, n=16, shard_size=4)
    build_dataset(two, n=16, shard_size=16)

    _, val_one = load_teacher_dataset(one).split(seed=0)
    _, val_two = load_teacher_dataset(two).split(seed=0)

    assert [e.example_id for e in val_one] == [e.example_id for e in val_two]


def test_duplicates_are_removed_and_counted(tmp_path):
    build_dataset(tmp_path, n=5, shard_size=10)
    # A shard re-copied from another session, as a botched Drive restore would leave.
    original = tmp_path / shard_name(0)
    manifest = DatasetManifest.read(tmp_path)
    duplicate = tmp_path / shard_name(1)
    duplicate.write_text(original.read_text(encoding="utf-8"), encoding="utf-8")
    manifest.add_shard(ShardRecord(name=shard_name(1), n_records=5, complete=True,
                                   sha256=None))
    manifest.write(tmp_path)

    dataset = load_teacher_dataset(tmp_path)

    assert len(dataset) == 5
    assert dataset.stats.n_duplicates == 5


def test_an_edited_record_is_dropped_with_a_reason(tmp_path):
    build_dataset(tmp_path, n=4, shard_size=10)
    shard = tmp_path / shard_name(0)
    lines = shard.read_text(encoding="utf-8").splitlines()
    record = json.loads(lines[0])
    record["teacher_answer"] = "tampered after generation"
    lines[0] = json.dumps(record)
    shard.write_text("\n".join(lines) + "\n", encoding="utf-8")

    dataset = load_teacher_dataset(tmp_path)

    assert len(dataset) == 3
    assert any("hash mismatch" in reason for reason in dataset.stats.dropped_reasons)


def test_mixed_teacher_models_are_surfaced(tmp_path):
    """A dataset stitched from two teachers is not one dataset."""
    build_dataset(tmp_path / "a", n=4, prefix="a",
                  teacher_model="Qwen/Qwen3.8-27B", shard_size=10)
    build_dataset(tmp_path / "b", n=4, prefix="b",
                  teacher_model="Some/Other-Model", shard_size=10)
    combined = tmp_path / "combined"
    combined.mkdir()
    for index, source in enumerate((tmp_path / "a", tmp_path / "b")):
        (combined / shard_name(index)).write_text(
            (source / shard_name(0)).read_text(encoding="utf-8"), encoding="utf-8"
        )

    dataset = load_teacher_dataset(combined, verified_only=False)

    assert len(dataset.stats.teacher_models) == 2
    assert "2 different teacher models present" in dataset.stats.render()


def test_mixed_reasoning_modes_are_surfaced(tmp_path):
    build_dataset(tmp_path / "a", n=3, mode="xhigh", prefix="a", shard_size=10)
    build_dataset(tmp_path / "b", n=3, mode="low", prefix="b", shard_size=10)
    combined = tmp_path / "combined"
    combined.mkdir()
    for index, source in enumerate((tmp_path / "a", tmp_path / "b")):
        (combined / shard_name(index)).write_text(
            (source / shard_name(0)).read_text(encoding="utf-8"), encoding="utf-8"
        )

    dataset = load_teacher_dataset(combined, verified_only=False)

    assert set(dataset.stats.reasoning_modes) == {"xhigh", "low"}
    assert "mixed reasoning modes" in dataset.stats.render()


def test_filters_report_what_they_removed(tmp_path):
    build_dataset(tmp_path, n=10, shard_size=20)
    dataset = load_teacher_dataset(
        tmp_path, filter=DatasetFilter(categories=("physics",))
    )
    assert len(dataset) == 0
    assert dataset.stats.dropped_reasons["category excluded"] == 10


def test_sft_formatting_can_include_or_exclude_reasoning(tmp_path):
    build_dataset(tmp_path, n=2, shard_size=10)
    example = load_teacher_dataset(tmp_path).examples[0]

    _, answer_only = format_sft_example(example, include_reasoning=False)
    _, with_reasoning = format_sft_example(example, include_reasoning=True)

    assert "<think>" not in answer_only
    assert "<think>" in with_reasoning
    assert answer_only in with_reasoning


def test_loading_a_missing_dataset_fails_clearly(tmp_path):
    with pytest.raises(FileNotFoundError, match="teacher dataset not found"):
        load_teacher_dataset(tmp_path / "absent")


# --- objectives -----------------------------------------------------------
def test_sft_is_implemented_and_kd_is_not():
    assert ObjectiveConfig(type=SFT).spec().available
    assert not ObjectiveConfig(type=LOGIT_KD).spec().available
    assert not ObjectiveConfig(type=MIXED_KD).spec().available
    assert ObjectiveConfig(type=LOGIT_KD).spec().status == NOT_IMPLEMENTED


def test_requesting_kd_raises_rather_than_running_sft():
    """The failure this guard exists for would make the KD-vs-SFT comparison meaningless."""
    with pytest.raises(ObjectiveUnavailable, match="NOT_IMPLEMENTED"):
        ObjectiveConfig(type=LOGIT_KD).require_available()


def test_the_kd_blocking_reason_explains_what_is_missing():
    reason = ObjectiveConfig(type=LOGIT_KD).spec().blocking_reason
    assert "logits" in reason
    assert "secretly SFT" in reason


def test_kd_parameters_set_on_an_sft_objective_are_flagged():
    """Usually means the objective was not actually switched."""
    problems = ObjectiveConfig(type=SFT, kd_alpha=0.5).validate()
    assert any("objective is sft" in p for p in problems)


def test_an_unknown_objective_is_rejected():
    with pytest.raises(ObjectiveUnavailable, match="unknown objective"):
        ObjectiveConfig(type="magic").spec()


def test_kd_against_a_dataset_with_no_logits_says_so(tmp_path):
    build_dataset(tmp_path, n=4)
    dataset = load_teacher_dataset(tmp_path)

    problems = check_dataset_supports(ObjectiveConfig(type=LOGIT_KD), dataset)

    assert any("no record in this dataset carries teacher logits" in p for p in problems)


def test_sft_against_a_real_dataset_validates(tmp_path):
    build_dataset(tmp_path, n=4)
    dataset = load_teacher_dataset(tmp_path)
    assert check_dataset_supports(ObjectiveConfig(type=SFT), dataset) == []


def test_the_mock_dataset_is_not_kd_ready(tmp_path):
    build_dataset(tmp_path, n=4)
    assert not load_teacher_dataset(tmp_path).kd_ready()


# --- provenance -----------------------------------------------------------
def test_an_unpinned_revision_is_recorded_as_a_gap():
    manifest = RunManifest(
        kind="teacher_generation",
        teacher=TeacherIdentity(model="Qwen/Qwen3.8-27B", revision=None,
                                chat_template_sha256="abc").to_dict(),
    )
    assert not manifest.fully_reproducible
    assert any("revision not pinned" in gap for gap in manifest.gaps())


def test_a_pinned_revision_with_hashes_has_no_teacher_gaps():
    manifest = RunManifest(
        kind="teacher_generation",
        teacher=TeacherIdentity(model="m", revision="abc123",
                                chat_template_sha256="def").to_dict(),
    )
    gaps = " ".join(manifest.gaps())
    assert "revision not pinned" not in gaps
    assert "chat template not hashed" not in gaps


def test_an_unhashed_template_is_a_gap_because_rendering_is_unverifiable():
    manifest = RunManifest(
        kind="teacher_generation",
        teacher=TeacherIdentity(model="m", revision="abc").to_dict(),
    )
    assert any("chat template not hashed" in gap for gap in manifest.gaps())


def test_digests_are_stable_across_key_order():
    assert sha256_json({"a": 1, "b": 2}) == sha256_json({"b": 2, "a": 1})
    assert sha256_text("x") != sha256_text("y")


def test_the_real_metadata_directory_hashes():
    """The files that decide how a prompt is rendered and tokenised."""
    identity = TeacherIdentity.from_metadata_dir(
        "Qwen/Qwen3.8-27B", "vendor/qwen38-metadata"
    )
    assert identity.chat_template_sha256
    assert identity.tokenizer_sha256
    assert identity.config_sha256
    assert not identity.is_pinned, "the upstream revision was never supplied"


def test_a_manifest_round_trips(tmp_path):
    manifest = RunManifest(kind="benchmark", reasoning_mode="xhigh")
    path = manifest.write(tmp_path / "manifest.json")
    assert RunManifest.read(path)["kind"] == "benchmark"


# --- paired evaluation and reasoning cost ---------------------------------
def paired(n=20, teacher_tokens=900, student_tokens=300):
    return [
        PairedRecord(
            example_id=f"e{i}", prompt_sha256="h", category="math",
            teacher={"total_output_tokens": teacher_tokens, "reasoning_tokens": 800,
                     "answer_tokens": 100, "correct": i % 5 != 0,
                     "latency_seconds": 2.0, "finish_reason": "stop"},
            student={"total_output_tokens": student_tokens, "reasoning_tokens": 200,
                     "answer_tokens": 100, "correct": i % 4 != 0,
                     "latency_seconds": 0.5, "finish_reason": "stop"},
        )
        for i in range(n)
    ]


def test_paired_summary_reports_both_sides_raw():
    summary = summarise_paired(paired())
    assert summary.teacher["accuracy"] == pytest.approx(0.8)
    assert summary.student["accuracy"] == pytest.approx(0.75)
    assert summary.teacher["median_reasoning_tokens"] == 800
    assert summary.student["median_reasoning_tokens"] == 200
    rendered = summary.render()
    assert "teacher" in rendered and "student" in rendered


def test_the_token_ratio_is_derived_not_primary():
    summary = summarise_paired(paired())
    assert summary.comparison["token_ratio"] == pytest.approx(300 / 900)
    assert summary.comparison["accuracy_delta"] == pytest.approx(-5.0)


def test_every_reported_metric_has_a_documented_formula():
    """No opaque efficiency score."""
    summary = summarise_paired(paired())
    for key in ("accuracy", "median_reasoning_tokens", "reasoning_share",
                "truncation_rate", "failure_rate"):
        assert key in METRIC_DEFINITIONS
    assert "accuracy_per_1k_reasoning_tokens" in summary.metric_definitions


def test_accuracy_per_reasoning_token_is_null_when_nothing_was_reasoned():
    """Dividing by zero reasoning is a different question, not a very good score."""
    records = [{"total_output_tokens": 10, "reasoning_tokens": 0, "answer_tokens": 10,
                "correct": True, "latency_seconds": 0.1}]
    assert summarise_side(records)["accuracy_per_1k_reasoning_tokens"] is None


def test_ungraded_examples_are_excluded_from_accuracy_not_counted_wrong():
    records = [
        {"total_output_tokens": 10, "reasoning_tokens": 0, "answer_tokens": 10,
         "correct": True, "latency_seconds": 0.1},
        {"total_output_tokens": 10, "reasoning_tokens": 0, "answer_tokens": 10,
         "correct": None, "latency_seconds": 0.1},
    ]
    summary = summarise_side(records)
    assert summary["n"] == 2
    assert summary["n_graded"] == 1
    assert summary["accuracy"] == 1.0


def test_truncation_is_measured_separately_from_failure():
    records = [
        {"total_output_tokens": 10, "reasoning_tokens": 0, "answer_tokens": 10,
         "correct": True, "latency_seconds": 0.1, "finish_reason": "length"},
        {"total_output_tokens": 10, "reasoning_tokens": 0, "answer_tokens": 10,
         "correct": True, "latency_seconds": 0.1, "finish_reason": "stop",
         "error": "boom"},
    ]
    summary = summarise_side(records)
    assert summary["truncation_rate"] == 0.5
    assert summary["failure_rate"] == 0.5


def test_token_budget_reports_coverage_alongside_accuracy():
    """A model answering 10% of prompts within budget and getting them right is not 100%."""
    records = [
        {"total_output_tokens": 100, "correct": True},
        {"total_output_tokens": 100, "correct": True},
        {"total_output_tokens": 5000, "correct": True},
        {"total_output_tokens": 5000, "correct": True},
    ]
    rows = {r["budget_tokens"]: r for r in accuracy_at_token_budget(records, (128,))}
    row = rows[128]
    assert row["coverage"] == 0.5
    assert row["accuracy_within_budget"] == 1.0
    assert row["accuracy_if_budget_enforced"] == 0.5


def test_the_sweep_table_is_ordered_by_effort():
    by_mode = {
        "xhigh": [{"total_output_tokens": 900, "reasoning_tokens": 800,
                   "answer_tokens": 100, "correct": True, "latency_seconds": 2.0}],
        "thinking_disabled": [{"total_output_tokens": 100, "reasoning_tokens": 0,
                               "answer_tokens": 100, "correct": False,
                               "latency_seconds": 0.2}],
        "low": [{"total_output_tokens": 300, "reasoning_tokens": 200,
                 "answer_tokens": 100, "correct": True, "latency_seconds": 0.6}],
    }
    rows = reasoning_sweep_table(by_mode)
    assert [r["mode"] for r in rows] == ["thinking_disabled", "low", "xhigh"]
    assert rows[0]["median_reasoning_tokens"] == 0


def test_per_category_breakdowns_survive_aggregation():
    records = paired(n=10)
    for record in records[:5]:
        record.category = "coding"
    summary = summarise_paired(records)
    assert set(summary.by_category) == {"math", "coding"}
    assert summary.by_category["coding"]["n"] == 5


def test_agreement_is_null_when_either_side_is_ungraded():
    record = PairedRecord(example_id="e", prompt_sha256="h",
                          teacher={"correct": True}, student={"correct": None})
    assert record.agreement() is None
